export const GET_QUSETION='GET_QUESTION';
export const QUSETION_HANDLER='QUSETION_HANDLER';
export const ATTEMPTS_HANDLER='ATTEMPTS_HANDLER';
export const GAME_OVER_HANDLER='GAME_OVER_HANDLER';

export const TRUE_ATTEMPT_HANDLER='TRUE_ATTEMPT_HANDLER';
export const ON_RESET_DATA='ON_RESET_DATA';